# AvNElytra Configuration File
# Version 1.0
# Speedscale controls the ratio between the "MaxSpeed" value and the Km/H value provided by CMI.

Elytra:
  Disabled: false
  Aliases: ["elytratoggle", "toggle", "elytra"]
RocketBoost:
  Disabled: false
  Aliases: ["fireworkboosttoggle", "rocketboosttoggle", "fireworktoggle", "rockettoggle", "firework", "rocket"]
TridentBoost:
  Disabled: false
  Aliases: ["tridentboosttoggle", "tridenttoggle", "trident"]
SpeedLimit:
  MaxSpeed: 0
  Scale: 10
  Aliases: ["speedcap", "speedlimit", "maxspeed", "speed", "zoomywoomybiggestspeedy"]